import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { generatePDFContent } from "@/lib/mockAI";
import { cn, copyToClipboard } from "@/lib/utils";
import { PAGE_HINTS, useAppStore } from "@/stores/appStore";
import type { PDFDocument, PDFSection } from "@/types";
import {
  BookOpen,
  ChevronLeft,
  ChevronRight,
  ClipboardCopy,
  Download,
  FileDown,
  Printer,
  RefreshCw,
  Wand2,
  ZoomIn,
  ZoomOut,
} from "lucide-react";
import { AnimatePresence, motion } from "motion/react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

// ── Constants ──────────────────────────────────────────────────────────────────

const DOC_TYPES = [
  "Academic Report",
  "Technical Paper",
  "Project Documentation",
  "Thesis Chapter",
  "Manual",
];

const DEPARTMENTS = [
  "CSE",
  "ECE",
  "EEE",
  "AI & DS",
  "AI & ML",
  "CIVIL",
  "MECH",
  "IT",
];

const SECTION_OPTIONS = [
  { id: "cover", label: "Cover Page" },
  { id: "abstract", label: "Abstract" },
  { id: "intro", label: "Introduction" },
  { id: "methodology", label: "Methodology" },
  { id: "results", label: "Results" },
  { id: "conclusion", label: "Conclusion" },
  { id: "references", label: "References" },
  { id: "appendix", label: "Appendix" },
];

const STYLES = ["Minimal Clean", "Academic Formal", "Modern Tech", "Creative"];

const SAMPLE_TOPICS = [
  "Smart Traffic Management System",
  "AI-based Recommendation System",
  "Renewable Energy Monitoring",
];

// ── Page grouping ─────────────────────────────────────────────────────────────

function buildPages(sections: PDFSection[]): PDFSection[][] {
  const pages: PDFSection[][] = [];
  for (let i = 0; i < sections.length; ) {
    const curr = sections[i];
    if (curr.type === "cover" || curr.type === "highlight") {
      pages.push([curr]);
      i++;
    } else if (i + 1 < sections.length) {
      pages.push([curr, sections[i + 1]]);
      i += 2;
    } else {
      pages.push([curr]);
      i++;
    }
  }
  return pages;
}

// ── Paper section renderers ───────────────────────────────────────────────────

function CoverPage({
  section,
  title,
  author,
}: {
  section: PDFSection;
  title: string;
  author: string;
}) {
  return (
    <div className="flex flex-col items-center justify-center min-h-[420px] text-center relative overflow-hidden">
      <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-blue-500 via-purple-500 to-cyan-500 rounded-t-sm" />
      <div className="absolute bottom-0 left-0 w-full h-1 bg-gradient-to-r from-cyan-500 via-blue-500 to-purple-500 opacity-60" />
      <div className="absolute top-8 right-8 w-20 h-20 rounded-full bg-gradient-to-br from-blue-500/10 to-purple-500/10 blur-xl" />
      <div className="absolute bottom-8 left-8 w-16 h-16 rounded-full bg-gradient-to-br from-cyan-500/10 to-blue-500/10 blur-xl" />
      <div className="relative z-10 px-8 py-12">
        <div className="mb-6 flex justify-center">
          <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-blue-500 to-purple-600 shadow-lg">
            <BookOpen size={26} className="text-white" />
          </div>
        </div>
        <h1
          className="text-2xl font-bold text-slate-800 leading-snug mb-4 max-w-sm mx-auto"
          style={{ fontFamily: "inherit" }}
        >
          {title}
        </h1>
        <div className="w-16 h-0.5 bg-gradient-to-r from-blue-500 to-cyan-500 mx-auto mb-5" />
        <p className="text-slate-500 text-sm font-medium mb-1">
          Academic Document
        </p>
        <div className="mt-6 space-y-1 text-slate-400 text-xs">
          {section.content.split("\n").map((line) => (
            <p key={line || " "}>{line}</p>
          ))}
        </div>
        <div className="mt-8 inline-flex items-center gap-1.5 rounded-full border border-blue-200 bg-blue-50 px-3 py-1 text-[10px] font-semibold text-blue-600">
          <span className="h-1.5 w-1.5 rounded-full bg-blue-500" />
          Generated by AI THOZHANX 2.O
        </div>
        <p className="mt-3 text-[10px] text-slate-300">{author}</p>
      </div>
    </div>
  );
}

function AbstractBlock({ section }: { section: PDFSection }) {
  return (
    <div className="px-8 py-6">
      <h2 className="text-xs font-bold text-slate-700 uppercase tracking-wider mb-3 flex items-center gap-2">
        <span className="h-3 w-1 rounded-full bg-purple-500 inline-block" />
        {section.heading}
      </h2>
      <div className="bg-slate-50 rounded-lg p-4 border-l-2 border-purple-400">
        <p className="text-slate-600 text-sm leading-relaxed italic">
          {section.content}
        </p>
      </div>
    </div>
  );
}

function HighlightBlock({ section }: { section: PDFSection }) {
  return (
    <div className="px-8 py-6">
      <div className="rounded-xl border border-cyan-200 bg-gradient-to-r from-cyan-50 to-blue-50 p-5">
        <div className="flex items-start gap-3">
          <div className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-cyan-400 to-blue-500">
            <span className="text-white text-xs font-bold">!</span>
          </div>
          <div>
            <div className="flex items-center gap-2 mb-2">
              <h3 className="text-sm font-bold text-cyan-700">
                {section.heading}
              </h3>
              <Badge className="bg-cyan-100 text-cyan-600 border-cyan-200 text-[9px] px-1.5 py-0">
                Key Insight
              </Badge>
            </div>
            <p className="text-slate-600 text-sm leading-relaxed">
              {section.content}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

function ConclusionBlock({ section }: { section: PDFSection }) {
  return (
    <div className="px-8 py-6">
      <h2 className="text-xs font-bold text-slate-700 uppercase tracking-wider mb-3 flex items-center gap-2">
        <span className="h-3 w-1 rounded-full bg-indigo-500 inline-block" />
        {section.heading}
      </h2>
      <div className="bg-gradient-to-br from-indigo-50 to-purple-50 rounded-lg p-4 border border-indigo-100">
        <p className="text-slate-600 text-sm leading-relaxed whitespace-pre-wrap">
          {section.content}
        </p>
      </div>
    </div>
  );
}

function BodySection({ section }: { section: PDFSection }) {
  return (
    <div className="px-8 py-5">
      <h2 className="text-xs font-bold text-slate-700 uppercase tracking-wider mb-3 flex items-center gap-2">
        <span className="h-3 w-1 rounded-full bg-blue-400 inline-block" />
        {section.heading}
      </h2>
      <p className="text-slate-600 text-sm leading-relaxed whitespace-pre-wrap">
        {section.content}
      </p>
    </div>
  );
}

function TOCPage({ sections }: { sections: PDFSection[] }) {
  const sectionLabels: Record<PDFSection["type"], string> = {
    cover: "Cover Page",
    abstract: "Abstract",
    intro: "Introduction",
    section: "Body Section",
    highlight: "Key Insights",
    conclusion: "Conclusion",
  };
  return (
    <div className="px-8 py-8">
      <h2 className="text-base font-bold text-slate-800 mb-1">
        Table of Contents
      </h2>
      <div className="w-12 h-0.5 bg-gradient-to-r from-blue-500 to-cyan-400 mb-5" />
      <div className="space-y-2">
        {sections.map((s, tocIdx) => (
          <div
            key={`${s.type}-${s.heading}`}
            className="flex items-center gap-2"
          >
            <span className="text-slate-300 text-xs font-mono w-5 text-right">
              {tocIdx + 1}.
            </span>
            <div className="flex-1 flex items-end gap-1">
              <span className="text-slate-600 text-sm">
                {s.heading !== "📌 Key Insight" ? s.heading : "Key Insights"}
              </span>
              <span className="flex-1 border-b border-dotted border-slate-200 mb-1" />
              <span className="text-slate-400 text-xs font-mono">
                {tocIdx + 1}
              </span>
            </div>
            <Badge
              variant="outline"
              className="text-[9px] px-1.5 border-slate-200 text-slate-400"
            >
              {sectionLabels[s.type]}
            </Badge>
          </div>
        ))}
      </div>
      <p className="mt-8 text-[10px] text-slate-300 text-center">
        Generated by AI THOZHANX 2.O • © 2026 AI THOZHANX
      </p>
    </div>
  );
}

function PDFPageContent({
  page,
  doc,
}: { page: PDFSection[]; doc: PDFDocument }) {
  if (page.length === 1 && page[0].type === "cover") {
    return (
      <CoverPage section={page[0]} title={doc.title} author={doc.author} />
    );
  }
  return (
    <div className="divide-y divide-slate-100">
      {page.map((section) => {
        if (section.type === "abstract")
          return <AbstractBlock key={section.heading} section={section} />;
        if (section.type === "highlight")
          return <HighlightBlock key={section.heading} section={section} />;
        if (section.type === "conclusion")
          return <ConclusionBlock key={section.heading} section={section} />;
        return <BodySection key={section.heading} section={section} />;
      })}
    </div>
  );
}

// ── Main component ────────────────────────────────────────────────────────────

export default function PdfPage() {
  const { setRobotState, setCurrentPageHint, addToHistory } = useAppStore();

  const [topic, setTopic] = useState("");
  const [docType, setDocType] = useState("Academic Report");
  const [department, setDepartment] = useState("CSE");
  const [selectedSections, setSelectedSections] = useState<Set<string>>(
    new Set(["cover", "abstract", "intro", "conclusion"]),
  );
  const [style, setStyle] = useState("Academic Formal");
  const [loading, setLoading] = useState(false);
  const [doc, setDoc] = useState<PDFDocument | null>(null);
  const [pages, setPages] = useState<PDFSection[][]>([]);
  const [currentPage, setCurrentPage] = useState(0);
  const [zoom, setZoom] = useState(1);

  // Set page hint on mount + pre-fill from localStorage
  useEffect(() => {
    setCurrentPageHint(PAGE_HINTS["/pdf"]);
    setRobotState("idle");
    const pending = localStorage.getItem("thozhanx-pending-prompt-pdf");
    if (pending) {
      setTopic(pending);
      localStorage.removeItem("thozhanx-pending-prompt-pdf");
    }
  }, [setCurrentPageHint, setRobotState]);

  const hasCover = pages.length > 0 && pages[0][0]?.type === "cover";
  // Page layout: cover(1) + TOC(1) + rest-of-content-pages
  const totalDisplayPages = doc
    ? (hasCover ? 1 : 0) + 1 + (pages.length - (hasCover ? 1 : 0))
    : 0;

  const generate = async () => {
    if (!topic.trim()) {
      toast.error("Please enter a document topic");
      return;
    }
    setLoading(true);
    setRobotState("thinking");
    await new Promise((r) => setTimeout(r, 2200));
    const result = generatePDFContent(topic);
    setDoc(result);
    const built = buildPages(result.sections);
    setPages(built);
    setCurrentPage(0);
    setLoading(false);

    setRobotState("celebration");
    setTimeout(() => setRobotState("idle"), 2000);

    addToHistory({
      moduleType: "pdf",
      prompt: topic.slice(0, 60),
      output: result.title,
    });
    toast.success("PDF document generated!");
  };

  const toggleSection = (id: string) => {
    setSelectedSections((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const handlePrint = () => {
    window.print();
    toast.success("Print dialog opened");
  };

  const handleCopyAll = async () => {
    if (!doc) return;
    const text = [
      doc.title,
      doc.author,
      ...doc.sections.map((s) => `${s.heading}\n\n${s.content}`),
    ].join("\n\n---\n\n");
    await copyToClipboard(text);
    toast.success("Copied all text to clipboard");
  };

  const handleDownloadPDF = async () => {
    if (!doc) return;
    toast.loading("Rendering PDF…", { id: "pdf-dl" });
    try {
      const paperEl = document.querySelector<HTMLElement>(".pdf-paper");
      if (!paperEl) throw new Error("Paper element not found");

      const [{ jsPDF }, html2canvas] = await Promise.all([
        import("jspdf"),
        import("html2canvas").then((m) => m.default),
      ]);

      // Temporarily reset zoom transform for accurate capture
      const parent = paperEl.parentElement;
      const prevTransform = parent?.style.transform ?? "";
      if (parent) parent.style.transform = "scale(1)";

      const canvas = await html2canvas(paperEl, {
        scale: 2,
        useCORS: true,
        backgroundColor: "#ffffff",
        logging: false,
      });

      if (parent) parent.style.transform = prevTransform;

      const imgW = 595; // A4 width in points
      const imgH = (canvas.height / canvas.width) * imgW;
      const pdf = new jsPDF({
        orientation: "portrait",
        unit: "pt",
        format: "a4",
      });
      const pageH = 842; // A4 height in points
      let yPos = 0;
      while (yPos < imgH) {
        if (yPos > 0) pdf.addPage();
        const remainH = Math.min(pageH, imgH - yPos);
        const srcY = (yPos / imgH) * canvas.height;
        const srcH = (remainH / imgH) * canvas.height;
        const sliceCanvas = document.createElement("canvas");
        sliceCanvas.width = canvas.width;
        sliceCanvas.height = srcH;
        const sCtx = sliceCanvas.getContext("2d");
        if (sCtx) {
          sCtx.drawImage(canvas, 0, -srcY, canvas.width, canvas.height);
        }
        const sliceImg = sliceCanvas.toDataURL("image/jpeg", 0.95);
        pdf.addImage(sliceImg, "JPEG", 0, 0, imgW, remainH);
        yPos += pageH;
      }

      pdf.save(`thozhanx-document-${Date.now()}.pdf`);
      toast.success("PDF downloaded!", { id: "pdf-dl" });
    } catch (err) {
      console.error(err);
      toast.error("PDF export failed", { id: "pdf-dl" });
    }
  };

  // Determine which content to show for a given display page index
  const renderDisplayPage = (pageIdx: number) => {
    if (!doc) return null;
    // Page 0 = cover (if exists) or TOC
    if (hasCover) {
      if (pageIdx === 0) return <PDFPageContent page={pages[0]} doc={doc} />;
      if (pageIdx === 1) return <TOCPage sections={doc.sections} />;
      const contentIdx = pageIdx - 2 + 1; // offset: skip cover(pages[0])
      if (contentIdx < pages.length)
        return <PDFPageContent page={pages[contentIdx]} doc={doc} />;
    } else {
      if (pageIdx === 0) return <TOCPage sections={doc.sections} />;
      const contentIdx = pageIdx - 1;
      if (contentIdx < pages.length)
        return <PDFPageContent page={pages[contentIdx]} doc={doc} />;
    }
    return null;
  };

  return (
    <div className="min-h-full p-4 md:p-6" data-ocid="pdf.page">
      <style>{`
        @media print {
          .no-print { display: none !important; }
          .pdf-paper { box-shadow: none !important; border: none !important; }
          body { background: white; }
        }
      `}</style>

      {/* ── Header ── */}
      <div className="mb-6 no-print">
        <div className="flex items-center gap-3 mb-1">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-blue-500 to-purple-600 shadow-lg shadow-blue-500/30">
            <FileDown size={20} className="text-white" />
          </div>
          <div>
            <h1 className="font-display text-2xl font-bold gradient-text">
              PDF Generator
            </h1>
            <p className="text-xs text-muted-foreground">
              Claude AI Style — Structured academic documents with design
            </p>
          </div>
        </div>
      </div>

      <div className="flex flex-col lg:flex-row gap-5">
        {/* ── Left panel ── */}
        <div className="lg:w-80 shrink-0 space-y-4 no-print">
          {/* Topic */}
          <div className="glassmorphism rounded-2xl p-4 space-y-3">
            <div className="space-y-1.5">
              <Label
                htmlFor="pdf-topic"
                className="text-xs font-semibold text-muted-foreground uppercase tracking-wider"
              >
                Document Topic
              </Label>
              <Input
                id="pdf-topic"
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                placeholder="e.g., Smart Traffic Management System"
                className="bg-background/50 border-border h-10 text-sm"
                data-ocid="pdf.topic.input"
                onKeyDown={(e) => {
                  if (e.key === "Enter") generate();
                }}
              />
              <div className="flex flex-wrap gap-1 pt-1">
                {SAMPLE_TOPICS.map((t, idx) => (
                  <button
                    type="button"
                    key={t}
                    onClick={() => setTopic(t)}
                    className="text-[10px] rounded-full border border-border/60 bg-muted/40 px-2 py-0.5 text-muted-foreground hover:bg-primary/10 hover:text-primary hover:border-primary/30 transition-smooth"
                    data-ocid={`pdf.sample.${idx + 1}`}
                  >
                    {t}
                  </button>
                ))}
              </div>
            </div>

            {/* Doc type */}
            <div className="space-y-1.5">
              <Label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                Document Type
              </Label>
              <div className="grid grid-cols-1 gap-1">
                {DOC_TYPES.map((t) => (
                  <button
                    type="button"
                    key={t}
                    onClick={() => setDocType(t)}
                    data-ocid={`pdf.doctype.${t.toLowerCase().replace(/\s+/g, "_")}`}
                    className={cn(
                      "text-left text-xs px-3 py-2 rounded-lg border transition-smooth",
                      docType === t
                        ? "border-primary/40 bg-primary/10 text-primary font-semibold"
                        : "border-border/40 bg-muted/20 text-muted-foreground hover:bg-muted/50",
                    )}
                  >
                    {t}
                  </button>
                ))}
              </div>
            </div>

            {/* Department */}
            <div className="space-y-1.5">
              <Label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                Department
              </Label>
              <div className="flex flex-wrap gap-1">
                {DEPARTMENTS.map((d) => (
                  <button
                    type="button"
                    key={d}
                    onClick={() => setDepartment(d)}
                    data-ocid={`pdf.dept.${d.toLowerCase().replace(/[\s&]+/g, "_")}`}
                    className={cn(
                      "text-[10px] px-2 py-0.5 rounded-full border transition-smooth",
                      department === d
                        ? "border-secondary/50 bg-secondary/15 text-secondary font-semibold"
                        : "border-border/40 bg-muted/20 text-muted-foreground hover:bg-muted/40",
                    )}
                  >
                    {d}
                  </button>
                ))}
              </div>
            </div>
          </div>

          {/* Sections */}
          <div className="glassmorphism rounded-2xl p-4">
            <Label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider block mb-2">
              Include Sections
            </Label>
            <div className="grid grid-cols-2 gap-1.5">
              {SECTION_OPTIONS.map((s) => (
                <div key={s.id} className="flex items-center gap-2">
                  <Checkbox
                    id={`sec-${s.id}`}
                    checked={selectedSections.has(s.id)}
                    onCheckedChange={() => toggleSection(s.id)}
                    data-ocid={`pdf.section_toggle.${s.id}`}
                    className="data-[state=checked]:bg-primary data-[state=checked]:border-primary"
                  />
                  <label
                    htmlFor={`sec-${s.id}`}
                    className="text-xs text-muted-foreground cursor-pointer select-none"
                  >
                    {s.label}
                  </label>
                </div>
              ))}
            </div>
          </div>

          {/* Style */}
          <div className="glassmorphism rounded-2xl p-4">
            <Label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider block mb-2">
              Style
            </Label>
            <div className="grid grid-cols-2 gap-1">
              {STYLES.map((s) => (
                <button
                  type="button"
                  key={s}
                  onClick={() => setStyle(s)}
                  data-ocid={`pdf.style.${s.toLowerCase().replace(/\s+/g, "_")}`}
                  className={cn(
                    "text-[10px] px-2 py-1.5 rounded-lg border transition-smooth",
                    style === s
                      ? "border-accent/50 bg-accent/15 text-accent font-semibold"
                      : "border-border/40 bg-muted/20 text-muted-foreground hover:bg-muted/40",
                  )}
                >
                  {s}
                </button>
              ))}
            </div>
          </div>

          {/* Generate */}
          <Button
            onClick={generate}
            disabled={loading || !topic.trim()}
            className="w-full h-11 bg-gradient-to-r from-blue-500 to-purple-600 hover:from-blue-600 hover:to-purple-700 text-white border-0 font-semibold shadow-lg shadow-blue-500/25"
            data-ocid="pdf.generate.submit_button"
          >
            {loading ? (
              <>
                <RefreshCw size={15} className="mr-2 animate-spin" />
                Generating Document…
              </>
            ) : (
              <>
                <Wand2 size={15} className="mr-2" />
                Generate PDF
              </>
            )}
          </Button>
        </div>

        {/* ── Right panel ── */}
        <div className="flex-1 min-w-0">
          {/* Loading */}
          {loading && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="glassmorphism rounded-2xl p-14 text-center"
              data-ocid="pdf.loading_state"
            >
              <div className="flex justify-center mb-4">
                <div className="relative h-14 w-14">
                  <div className="absolute inset-0 rounded-xl bg-gradient-to-br from-blue-500 to-purple-600 animate-pulse" />
                  <div className="absolute inset-0 flex items-center justify-center">
                    <FileDown size={26} className="text-white" />
                  </div>
                </div>
              </div>
              <p className="text-sm font-semibold text-foreground mb-1">
                Generating your PDF document
              </p>
              <p className="text-xs text-muted-foreground">
                Structuring academic content with Claude AI style…
              </p>
              <div className="mt-4 flex justify-center gap-1">
                {[0, 1, 2].map((i) => (
                  <div
                    key={i}
                    className="h-2 w-2 rounded-full bg-primary animate-bounce"
                    style={{ animationDelay: `${i * 0.15}s` }}
                  />
                ))}
              </div>
            </motion.div>
          )}

          {/* Empty state */}
          {!doc && !loading && (
            <div
              className="glassmorphism rounded-2xl p-14 text-center"
              data-ocid="pdf.empty_state"
            >
              <div className="flex justify-center mb-4">
                <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-muted/50">
                  <FileDown size={28} className="text-muted-foreground/40" />
                </div>
              </div>
              <p className="font-semibold text-foreground/60 mb-1">
                No document generated yet
              </p>
              <p className="text-xs text-muted-foreground max-w-xs mx-auto">
                Enter a topic and click Generate to create a structured academic
                PDF with A4 paper preview.
              </p>
              <div className="mt-6 flex flex-wrap justify-center gap-2">
                {[
                  "Cover Page",
                  "Table of Contents",
                  "Academic Sections",
                  "Key Insights",
                ].map((f) => (
                  <span
                    key={f}
                    className="text-[10px] rounded-full border border-border/50 bg-muted/30 px-2.5 py-1 text-muted-foreground"
                  >
                    {f}
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* Document preview */}
          <AnimatePresence>
            {doc && !loading && (
              <motion.div
                initial={{ opacity: 0, y: 16 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0 }}
                data-ocid="pdf.result.section"
              >
                {/* Toolbar */}
                <div className="no-print flex items-center justify-between mb-3 gap-2 flex-wrap">
                  <div className="flex items-center gap-2 flex-wrap">
                    <Badge className="bg-primary/10 text-primary border-primary/20 text-xs gap-1.5">
                      <FileDown size={11} />
                      {totalDisplayPages} Pages
                    </Badge>
                    <Badge
                      variant="outline"
                      className="text-[10px] text-muted-foreground border-border/50"
                    >
                      {docType} · {department}
                    </Badge>
                    <Badge
                      variant="outline"
                      className="text-[10px] text-muted-foreground border-border/50"
                    >
                      {style}
                    </Badge>
                  </div>
                  <div className="flex items-center gap-1.5 flex-wrap">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() =>
                        setZoom((z) => Math.max(0.6, +(z - 0.1).toFixed(1)))
                      }
                      className="h-8 w-8 p-0 border-border/50"
                      data-ocid="pdf.zoom_out.button"
                      aria-label="Zoom out"
                    >
                      <ZoomOut size={13} />
                    </Button>
                    <span className="text-xs text-muted-foreground font-mono w-10 text-center">
                      {Math.round(zoom * 100)}%
                    </span>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() =>
                        setZoom((z) => Math.min(1.4, +(z + 0.1).toFixed(1)))
                      }
                      className="h-8 w-8 p-0 border-border/50"
                      data-ocid="pdf.zoom_in.button"
                      aria-label="Zoom in"
                    >
                      <ZoomIn size={13} />
                    </Button>
                    <div className="w-px h-5 bg-border mx-0.5" />
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={handlePrint}
                      className="h-8 px-3 border-border/50 text-xs gap-1.5"
                      data-ocid="pdf.print.button"
                    >
                      <Printer size={12} />
                      Print PDF
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={handleCopyAll}
                      className="h-8 px-3 border-border/50 text-xs gap-1.5"
                      data-ocid="pdf.copy.button"
                    >
                      <ClipboardCopy size={12} />
                      Copy
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={handleDownloadPDF}
                      className="h-8 px-3 border-border/50 text-xs gap-1.5"
                      data-ocid="pdf.download.button"
                    >
                      <Download size={12} />
                      Download PDF
                    </Button>
                  </div>
                </div>

                {/* A4 Paper */}
                <div className="flex justify-center overflow-x-auto pb-4">
                  <div
                    style={{
                      transform: `scale(${zoom})`,
                      transformOrigin: "top center",
                      transition: "transform 0.25s cubic-bezier(0.4,0,0.2,1)",
                    }}
                  >
                    <div
                      className="pdf-paper bg-white rounded-sm shadow-2xl shadow-black/30"
                      style={{
                        width: "595px",
                        minHeight: "842px",
                        position: "relative",
                      }}
                      data-ocid="pdf.paper"
                    >
                      {/* Paper header strip */}
                      <div className="flex items-center justify-between px-8 pt-5 pb-3 border-b border-slate-100">
                        <div className="flex items-center gap-2">
                          <div className="h-4 w-4 rounded bg-gradient-to-br from-blue-500 to-purple-600" />
                          <span className="text-[10px] font-semibold text-slate-400 uppercase tracking-widest">
                            AI THOZHANX 2.O
                          </span>
                        </div>
                        <span className="text-[10px] text-slate-300">
                          {docType} · {department}
                        </span>
                      </div>

                      {/* Page content */}
                      <div className="pb-12">
                        <AnimatePresence mode="wait">
                          <motion.div
                            key={currentPage}
                            initial={{ opacity: 0, x: 8 }}
                            animate={{ opacity: 1, x: 0 }}
                            exit={{ opacity: 0, x: -8 }}
                            transition={{ duration: 0.18 }}
                          >
                            {renderDisplayPage(currentPage)}
                          </motion.div>
                        </AnimatePresence>
                      </div>

                      {/* Paper footer */}
                      <div className="absolute bottom-0 left-0 right-0 flex items-center justify-between px-8 py-3 border-t border-slate-100">
                        <span className="text-[9px] text-slate-300 italic">
                          Generated by AI THOZHANX 2.O · Educational Use Only
                        </span>
                        <span className="text-[9px] text-slate-300 font-mono">
                          {currentPage + 1}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Page navigation */}
                <div
                  className="no-print flex items-center justify-center gap-3 mt-4"
                  data-ocid="pdf.pagination"
                >
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setCurrentPage((p) => Math.max(0, p - 1))}
                    disabled={currentPage === 0}
                    className="h-8 w-8 p-0 border-border/50"
                    data-ocid="pdf.pagination_prev"
                    aria-label="Previous page"
                  >
                    <ChevronLeft size={14} />
                  </Button>
                  <div className="flex items-center gap-1">
                    {Array.from({ length: totalDisplayPages }, (_, i) => (
                      <button
                        type="button"
                        key={`page-dot-${i + 1}`}
                        onClick={() => setCurrentPage(i)}
                        data-ocid={`pdf.page_dot.${i + 1}`}
                        className={cn(
                          "rounded-full transition-smooth",
                          i === currentPage
                            ? "h-2 w-6 bg-primary"
                            : "h-2 w-2 bg-muted-foreground/20 hover:bg-muted-foreground/40",
                        )}
                        aria-label={`Go to page ${i + 1}`}
                      />
                    ))}
                  </div>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() =>
                      setCurrentPage((p) =>
                        Math.min(totalDisplayPages - 1, p + 1),
                      )
                    }
                    disabled={currentPage === totalDisplayPages - 1}
                    className="h-8 w-8 p-0 border-border/50"
                    data-ocid="pdf.pagination_next"
                    aria-label="Next page"
                  >
                    <ChevronRight size={14} />
                  </Button>
                  <span className="text-xs text-muted-foreground ml-1">
                    Page {currentPage + 1} of {totalDisplayPages}
                  </span>
                </div>

                {/* Section overview grid */}
                <div
                  className="no-print mt-4 glassmorphism rounded-2xl p-4"
                  data-ocid="pdf.sections.list"
                >
                  <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-3">
                    Document Sections
                  </p>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
                    {doc.sections.map((s, i) => (
                      <div
                        key={`${s.type}-${i}`}
                        data-ocid={`pdf.section.item.${i + 1}`}
                        className={cn(
                          "rounded-lg border p-3 cursor-pointer transition-smooth hover:scale-[1.02]",
                          s.type === "cover" &&
                            "border-blue-200/50 bg-blue-500/5",
                          s.type === "abstract" &&
                            "border-purple-200/50 bg-purple-500/5",
                          s.type === "highlight" &&
                            "border-cyan-200/50 bg-cyan-500/5",
                          s.type === "conclusion" &&
                            "border-indigo-200/50 bg-indigo-500/5",
                          (s.type === "intro" || s.type === "section") &&
                            "border-border/40 bg-muted/20",
                        )}
                      >
                        <p className="text-[11px] font-semibold text-foreground/80 truncate">
                          {s.heading}
                        </p>
                        <p className="text-[10px] text-muted-foreground mt-0.5 capitalize">
                          {s.type}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
}
