import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { generateVideoScript } from "@/lib/mockAI";
import { copyToClipboard, downloadText, wordCount } from "@/lib/utils";
import { PAGE_HINTS, useAppStore } from "@/stores/appStore";
import type { VideoScene, VideoScript } from "@/types";
import {
  BookOpen,
  ChevronRight,
  Clock,
  Copy,
  Download,
  ExternalLink,
  Film,
  Layers,
  Pause,
  Play,
  Settings2,
  Sparkles,
  Video,
  Volume2,
  Wand2,
  Zap,
} from "lucide-react";
import { AnimatePresence, motion } from "motion/react";
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";

// ─── Constants ────────────────────────────────────────────────────────────────

const VIDEO_TYPES = [
  { value: "explainer", label: "Explainer Video", icon: "💡" },
  { value: "demo", label: "Demo Video", icon: "🖥️" },
  { value: "educational", label: "Educational Animation", icon: "🎓" },
  { value: "tutorial", label: "Tutorial", icon: "📋" },
] as const;

const DURATIONS = [
  { value: "30", label: "30 sec", seconds: 30 },
  { value: "60", label: "1 min", seconds: 60 },
  { value: "120", label: "2 min", seconds: 120 },
  { value: "300", label: "5 min", seconds: 300 },
] as const;

const STYLES = [
  {
    value: "professional",
    label: "Professional",
    color: "from-primary to-secondary",
  },
  { value: "casual", label: "Casual", color: "from-accent to-primary" },
  { value: "academic", label: "Academic", color: "from-secondary to-accent" },
  { value: "creative", label: "Creative", color: "from-accent to-secondary" },
] as const;

const SAMPLE_TOPICS = [
  "How IoT works",
  "Machine learning explained",
  "Solar energy systems",
  "Web development basics",
];

const VISUAL_CUES: Record<number, { label: string; color: string }> = {
  1: {
    label: "Cinematic Pan",
    color: "border-primary/40 bg-primary/10 text-primary",
  },
  2: {
    label: "Bullet Animation",
    color: "border-secondary/40 bg-secondary/10 text-secondary",
  },
  3: {
    label: "Flow Chart",
    color: "border-accent/40 bg-accent/10 text-accent",
  },
  4: {
    label: "Split Screen",
    color: "border-primary/40 bg-primary/10 text-primary",
  },
  5: {
    label: "Recap Slide",
    color: "border-secondary/40 bg-secondary/10 text-secondary",
  },
};

const PRODUCTION_NOTES = [
  { label: "Color Palette", value: "Deep navy → Electric blue → Cyan accent" },
  { label: "Typography", value: "Bold sans-serif headers, clean body text" },
  { label: "Music", value: "Ambient electronic / Lo-fi academic beat" },
  { label: "Voiceover", value: "Clear, professional, moderate pace (130 WPM)" },
  { label: "Transitions", value: "Smooth slide, fade-in, zoom-out" },
  { label: "Frame Rate", value: "24fps cinematic / 60fps for animations" },
  { label: "Resolution", value: "1920×1080 (Full HD) — export as MP4/WebM" },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────

function getNarrationForScene(
  scene: VideoScene,
  fullNarration: string,
): string {
  const sentences = fullNarration.split(/(?<=[.!?])\s+/).filter(Boolean);
  const perScene = Math.ceil(sentences.length / 5);
  const idx = scene.id - 1;
  const slice = sentences.slice(idx * perScene, (idx + 1) * perScene);
  return slice.join(" ") || `${scene.description.slice(0, 100)}...`;
}

function buildScriptText(script: VideoScript): string {
  const scenes = script.scenes
    .map(
      (s) =>
        `[Scene ${s.id}: ${s.title} — ${s.duration}s]\nVisual: ${s.description}\nNarration: ${getNarrationForScene(s, script.narration)}`,
    )
    .join("\n\n");
  return `VIDEO SCRIPT: ${script.title}\nTotal Duration: ${script.duration}s\n\nFULL NARRATION:\n${script.narration}\n\n---\nSCENE BREAKDOWN:\n\n${scenes}\n\nGenerated by AI THOZHANX 2.O | © 2026`;
}

function buildStoryboardText(script: VideoScript): string {
  return script.scenes
    .map(
      (s) =>
        `Scene ${s.id}: ${s.title}\nDuration: ${s.duration}s\nVisual: ${s.description}\nCue: ${VISUAL_CUES[s.id]?.label ?? "Animation"}`,
    )
    .join("\n\n---\n\n");
}

// ─── Mock Video Player ────────────────────────────────────────────────────────

function MockVideoPlayer({ script }: { script: VideoScript }) {
  const [playing, setPlaying] = useState(false);
  const [progress, setProgress] = useState(0);
  const [activeScene, setActiveScene] = useState(0);
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    if (playing) {
      intervalRef.current = setInterval(() => {
        setProgress((p) => {
          const next = p + 0.5;
          if (next >= 100) {
            setPlaying(false);
            return 100;
          }
          const sceneIndex = Math.floor((next / 100) * script.scenes.length);
          setActiveScene(Math.min(sceneIndex, script.scenes.length - 1));
          return next;
        });
      }, 60);
    } else {
      if (intervalRef.current) clearInterval(intervalRef.current);
    }
    return () => {
      if (intervalRef.current) clearInterval(intervalRef.current);
    };
  }, [playing, script.scenes.length]);

  const handleProgressClick = (e: React.MouseEvent<HTMLDivElement>) => {
    const rect = e.currentTarget.getBoundingClientRect();
    const pct = Math.round(((e.clientX - rect.left) / rect.width) * 100);
    setProgress(pct);
    setActiveScene(
      Math.min(
        Math.floor((pct / 100) * script.scenes.length),
        script.scenes.length - 1,
      ),
    );
  };

  const currentScene = script.scenes[activeScene];

  return (
    <div
      className="relative overflow-hidden rounded-2xl border border-white/10 bg-card"
      data-ocid="video.player.panel"
    >
      <div className="relative flex h-56 items-center justify-center overflow-hidden bg-gradient-to-br from-[oklch(0.1_0.02_265)] via-[oklch(0.14_0.04_280)] to-[oklch(0.1_0.03_205)]">
        <div className="pointer-events-none absolute inset-0 overflow-hidden">
          <div
            className="absolute -left-12 top-4 h-40 w-40 animate-pulse rounded-full opacity-30"
            style={{
              background:
                "radial-gradient(circle, oklch(0.65 0.24 258 / 0.6), transparent 70%)",
            }}
          />
          <div
            className="absolute -right-8 bottom-2 h-32 w-32 animate-pulse rounded-full opacity-20"
            style={{
              background:
                "radial-gradient(circle, oklch(0.7 0.24 205 / 0.6), transparent 70%)",
              animationDelay: "300ms",
            }}
          />
        </div>

        <AnimatePresence mode="wait">
          <motion.div
            key={activeScene}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            transition={{ duration: 0.4 }}
            className="relative z-10 flex flex-col items-center gap-2 px-10 text-center"
          >
            <Badge
              variant="outline"
              className="border-accent/40 bg-accent/10 text-accent text-[10px]"
            >
              Scene {currentScene?.id ?? 1} of {script.scenes.length}
            </Badge>
            <p className="font-display text-lg font-bold text-foreground leading-tight">
              {currentScene?.title ?? script.title}
            </p>
            <p className="max-w-sm text-xs text-muted-foreground line-clamp-2">
              {currentScene?.description ?? script.narration}
            </p>
            {currentScene && (
              <Badge
                variant="outline"
                className={`text-[10px] ${VISUAL_CUES[currentScene.id]?.color ?? "border-accent/30 text-accent"}`}
              >
                <Zap size={8} className="mr-0.5" />
                {VISUAL_CUES[currentScene.id]?.label ?? "Animation"}
              </Badge>
            )}
          </motion.div>
        </AnimatePresence>

        <button
          type="button"
          onClick={() => setPlaying((p) => !p)}
          className="absolute inset-0 flex items-center justify-center opacity-0 transition-opacity hover:opacity-100"
          aria-label={playing ? "Pause video" : "Play video"}
          data-ocid="video.player.toggle"
        >
          <div className="flex h-14 w-14 items-center justify-center rounded-full bg-primary/80 backdrop-blur-sm shadow-glow-blue transition-smooth hover:scale-110">
            {playing ? (
              <Pause size={22} className="text-primary-foreground" />
            ) : (
              <Play
                size={22}
                className="fill-primary-foreground text-primary-foreground ml-1"
              />
            )}
          </div>
        </button>
      </div>

      <div className="flex gap-px px-4 pt-3">
        {script.scenes.map((s, i) => (
          <button
            key={s.id}
            type="button"
            onClick={() => {
              const pct = (i / script.scenes.length) * 100;
              setProgress(pct);
              setActiveScene(i);
            }}
            className={`h-1 flex-1 rounded-full transition-smooth ${i === activeScene ? "bg-accent shadow-glow-cyan" : "bg-border hover:bg-accent/40"}`}
            title={s.title}
            data-ocid={`video.scene.track.${i + 1}`}
          />
        ))}
      </div>

      <div className="flex flex-col gap-2 px-4 py-3 bg-muted/30">
        <div
          role="slider"
          aria-label="Video progress"
          aria-valuenow={Math.round(progress)}
          aria-valuemin={0}
          aria-valuemax={100}
          tabIndex={0}
          className="group relative h-1.5 cursor-pointer overflow-hidden rounded-full bg-border"
          onClick={handleProgressClick}
          onKeyDown={(e) => {
            if (e.key === "ArrowRight")
              setProgress((p) => Math.min(100, p + 5));
            if (e.key === "ArrowLeft") setProgress((p) => Math.max(0, p - 5));
          }}
          data-ocid="video.player.progress"
        >
          <div
            className="h-full rounded-full bg-gradient-to-r from-primary to-accent transition-all duration-100"
            style={{ width: `${progress}%` }}
          />
          <div
            className="absolute top-1/2 -translate-y-1/2 h-3 w-3 rounded-full bg-accent opacity-0 group-hover:opacity-100 -translate-x-1/2 transition-opacity"
            style={{ left: `${progress}%` }}
          />
        </div>

        <div className="flex items-center gap-3 text-muted-foreground">
          <button
            type="button"
            onClick={() => setPlaying((p) => !p)}
            className="transition-smooth hover:text-foreground"
            aria-label={playing ? "Pause" : "Play"}
            data-ocid="video.player.play_button"
          >
            {playing ? <Pause size={16} /> : <Play size={16} />}
          </button>
          <span className="text-xs">
            {Math.round((progress / 100) * script.duration)}s /{" "}
            {script.duration}s
          </span>
          <span className="text-xs text-accent truncate">
            {currentScene?.title}
          </span>
          <div className="ml-auto flex items-center gap-2">
            <Volume2 size={14} />
            <Settings2
              size={14}
              className="transition-smooth hover:text-foreground cursor-pointer"
            />
            <Film size={14} />
          </div>
        </div>
      </div>
    </div>
  );
}

// ─── Scene Card ───────────────────────────────────────────────────────────────

function SceneCard({
  scene,
  index,
  narration,
  isLast,
}: {
  scene: VideoScene;
  index: number;
  narration: string;
  isLast: boolean;
}) {
  const [expanded, setExpanded] = useState(false);
  const cue = VISUAL_CUES[scene.id] ?? {
    label: "Animation",
    color: "border-accent/30 bg-accent/10 text-accent",
  };
  const sceneNarration = getNarrationForScene(scene, narration);

  return (
    <motion.div
      initial={{ opacity: 0, x: -16 }}
      animate={{ opacity: 1, x: 0 }}
      transition={{ delay: index * 0.08, duration: 0.4 }}
      className="flex gap-0"
      data-ocid={`video.scene.item.${index + 1}`}
    >
      <div className="flex w-10 shrink-0 flex-col items-center">
        <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-gradient-to-br from-primary/20 to-accent/20 border border-primary/30 mt-3">
          <span className="text-xs font-bold text-primary">{scene.id}</span>
        </div>
        {!isLast && (
          <div
            className="w-px flex-1 bg-gradient-to-b from-primary/30 to-transparent mt-1"
            style={{ minHeight: 20 }}
          />
        )}
      </div>

      <div className="flex-1 min-w-0 mb-3 ml-2">
        <div className="glass rounded-xl border border-primary/20 hover:border-accent/40 transition-smooth overflow-hidden p-4">
          <div className="flex items-start gap-2 flex-wrap mb-2">
            <span className="text-sm font-semibold text-foreground">
              {scene.title}
            </span>
            <div className="ml-auto flex items-center gap-1.5 shrink-0">
              <Badge variant="outline" className={`text-[10px] ${cue.color}`}>
                <Zap size={8} className="mr-0.5" />
                {cue.label}
              </Badge>
              <Badge
                variant="outline"
                className="text-[10px] border-border text-muted-foreground"
              >
                <Clock size={9} className="mr-1" />
                {scene.duration}s
              </Badge>
            </div>
          </div>

          <p className="text-xs text-muted-foreground leading-relaxed mb-2">
            <span className="font-medium text-foreground/70">Visual: </span>
            {scene.description}
          </p>

          <button
            type="button"
            onClick={() => setExpanded((e) => !e)}
            className="flex items-center gap-1 text-[10px] text-accent hover:text-accent/80 transition-smooth"
            data-ocid={`video.scene.narration.toggle.${index + 1}`}
          >
            <ChevronRight
              size={10}
              className={`transition-transform duration-200 ${expanded ? "rotate-90" : ""}`}
            />
            {expanded ? "Hide narration" : "Show narration"}
          </button>

          <AnimatePresence>
            {expanded && (
              <motion.div
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: "auto" }}
                exit={{ opacity: 0, height: 0 }}
                transition={{ duration: 0.2 }}
                className="overflow-hidden"
              >
                <p className="mt-2 text-xs text-foreground/80 leading-relaxed rounded-lg bg-muted/20 border border-border px-3 py-2 italic">
                  "{sceneNarration}"
                </p>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </motion.div>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────

export default function VideoGeneratorPage() {
  const { setRobotState, setCurrentPageHint, addToHistory } = useAppStore();

  const [topic, setTopic] = useState("");
  const [videoType, setVideoType] = useState<string>("explainer");
  const [duration, setDuration] = useState<string>("120");
  const [style, setStyle] = useState<string>("professional");
  const [loading, setLoading] = useState(false);
  const [genProgress, setGenProgress] = useState(0);
  const [result, setResult] = useState<VideoScript | null>(null);
  const [showSceneNarrations, setShowSceneNarrations] = useState(false);

  // Set page hint on mount + pre-fill from localStorage
  useEffect(() => {
    setCurrentPageHint(PAGE_HINTS["/video"]);
    setRobotState("idle");
    const pending = localStorage.getItem("thozhanx-pending-prompt-video");
    if (pending) {
      setTopic(pending);
      localStorage.removeItem("thozhanx-pending-prompt-video");
    }
  }, [setCurrentPageHint, setRobotState]);

  const generate = async () => {
    if (!topic.trim()) {
      toast.error("Please enter a video topic");
      return;
    }
    setLoading(true);
    setGenProgress(0);
    setResult(null);
    setShowSceneNarrations(false);
    setRobotState("thinking");

    const steps = [15, 35, 60, 80, 95, 100];
    for (const step of steps) {
      await new Promise((r) => setTimeout(r, 350));
      setGenProgress(step);
    }

    const script = generateVideoScript(topic);
    setResult(script);
    setLoading(false);

    setRobotState("celebration");
    setTimeout(() => setRobotState("idle"), 2000);

    addToHistory({
      moduleType: "video",
      prompt: topic.slice(0, 60),
      output: script.title,
    });
    toast.success("Video script generated!", {
      description: `${script.scenes.length} scenes • ${script.duration}s total`,
    });
  };

  const handleCopyScript = async () => {
    if (!result) return;
    await copyToClipboard(buildScriptText(result));
    toast.success("Full script copied to clipboard!");
  };

  const handleDownloadScript = async () => {
    if (!result) return;

    if (!window.MediaRecorder) {
      downloadText(
        buildScriptText(result),
        `${result.title.slice(0, 40).replace(/\s+/g, "-").toLowerCase()}-script.txt`,
      );
      toast.success("Script downloaded (MP4 not supported in this browser)");
      return;
    }

    toast.loading("Rendering video frames…", { id: "vid-dl" });

    try {
      const W = 1280;
      const H = 720;
      const canvas = document.createElement("canvas");
      canvas.width = W;
      canvas.height = H;
      const ctx = canvas.getContext("2d");
      if (!ctx) throw new Error("Canvas unavailable");

      const stream = canvas.captureStream(30);
      const mimeType = MediaRecorder.isTypeSupported("video/mp4;codecs=h264")
        ? "video/mp4"
        : MediaRecorder.isTypeSupported("video/webm;codecs=vp9")
          ? "video/webm;codecs=vp9"
          : "video/webm";
      const recorder = new MediaRecorder(stream, {
        mimeType,
        videoBitsPerSecond: 2_500_000,
      });
      const chunks: Blob[] = [];
      recorder.ondataavailable = (e) => {
        if (e.data.size > 0) chunks.push(e.data);
      };

      const scenes = result.scenes;
      const FPS = 30;
      const SCENE_DURATION_S = 2.5;
      const TOTAL_FRAMES = Math.ceil(scenes.length * SCENE_DURATION_S * FPS);

      const SCENE_COLORS: [string, string][] = [
        ["#1e1b4b", "#3730a3"],
        ["#0f172a", "#1e40af"],
        ["#0d1117", "#065f46"],
        ["#1a0533", "#6d28d9"],
        ["#0c1a2e", "#0e7490"],
      ];

      const drawScene = (scene: (typeof scenes)[0], progress: number) => {
        const colorPair = SCENE_COLORS[(scene.id - 1) % SCENE_COLORS.length];
        const bg = ctx.createLinearGradient(0, 0, W, H);
        bg.addColorStop(0, colorPair[0]);
        bg.addColorStop(1, colorPair[1]);
        ctx.fillStyle = bg;
        ctx.fillRect(0, 0, W, H);

        const orbX = W * 0.15 + Math.sin(progress * Math.PI * 2) * 40;
        const orbY = H * 0.2;
        const orb = ctx.createRadialGradient(orbX, orbY, 0, orbX, orbY, 250);
        orb.addColorStop(0, "rgba(139,92,246,0.35)");
        orb.addColorStop(1, "transparent");
        ctx.fillStyle = orb;
        ctx.fillRect(0, 0, W, H);

        const bar = ctx.createLinearGradient(0, 0, W, 0);
        bar.addColorStop(0, "#6366f1");
        bar.addColorStop(0.5, "#8b5cf6");
        bar.addColorStop(1, "#06b6d4");
        ctx.fillStyle = bar;
        ctx.fillRect(0, 0, W, 5);

        ctx.fillStyle = "rgba(99,102,241,0.3)";
        const badgeW = 160;
        const badgeH = 28;
        const badgeX = W / 2 - badgeW / 2;
        const badgeY = H * 0.18;
        const bR = 14;
        ctx.beginPath();
        ctx.moveTo(badgeX + bR, badgeY);
        ctx.lineTo(badgeX + badgeW - bR, badgeY);
        ctx.arcTo(badgeX + badgeW, badgeY, badgeX + badgeW, badgeY + bR, bR);
        ctx.lineTo(badgeX + badgeW, badgeY + badgeH - bR);
        ctx.arcTo(
          badgeX + badgeW,
          badgeY + badgeH,
          badgeX + badgeW - bR,
          badgeY + badgeH,
          bR,
        );
        ctx.lineTo(badgeX + bR, badgeY + badgeH);
        ctx.arcTo(badgeX, badgeY + badgeH, badgeX, badgeY + badgeH - bR, bR);
        ctx.lineTo(badgeX, badgeY + bR);
        ctx.arcTo(badgeX, badgeY, badgeX + bR, badgeY, bR);
        ctx.closePath();
        ctx.fill();
        ctx.strokeStyle = "rgba(99,102,241,0.6)";
        ctx.lineWidth = 1.5;
        ctx.stroke();

        ctx.font = "bold 13px 'Inter', sans-serif";
        ctx.fillStyle = "#a5b4fc";
        ctx.textAlign = "center";
        ctx.textBaseline = "middle";
        ctx.fillText(
          `Scene ${scene.id} of ${scenes.length}`,
          W / 2,
          badgeY + badgeH / 2,
        );

        const fadeIn = Math.min(1, progress * 3);
        ctx.globalAlpha = fadeIn;
        ctx.font = "bold 40px 'Inter', sans-serif";
        ctx.fillStyle = "#ffffff";
        ctx.textAlign = "center";
        ctx.textBaseline = "top";
        const titleWords = scene.title.split(" ");
        const titleLines: string[] = [];
        let titleCur = "";
        for (const w of titleWords) {
          const t = titleCur ? `${titleCur} ${w}` : w;
          if (ctx.measureText(t).width > W * 0.75 && titleCur) {
            titleLines.push(titleCur);
            titleCur = w;
          } else {
            titleCur = t;
          }
        }
        if (titleCur) titleLines.push(titleCur);
        const titleY = H * 0.35;
        titleLines.forEach((ln, i) => ctx.fillText(ln, W / 2, titleY + i * 52));

        ctx.font = "18px 'Inter', sans-serif";
        ctx.fillStyle = "rgba(255,255,255,0.65)";
        const descWords = scene.description.split(" ");
        const descLines: string[] = [];
        let descCur = "";
        for (const w of descWords) {
          const t = descCur ? `${descCur} ${w}` : w;
          if (ctx.measureText(t).width > W * 0.68 && descCur) {
            descLines.push(descCur);
            descCur = w;
          } else {
            descCur = t;
          }
        }
        if (descCur) descLines.push(descCur);
        const descY = titleY + titleLines.length * 52 + 30;
        descLines
          .slice(0, 3)
          .forEach((ln, i) => ctx.fillText(ln, W / 2, descY + i * 28));

        ctx.font = "14px monospace";
        ctx.fillStyle = "rgba(6,182,212,0.9)";
        ctx.fillText(`⏱ ${scene.duration}s`, W / 2, H * 0.82);

        ctx.globalAlpha = 0.4;
        ctx.fillStyle = "rgba(255,255,255,0.15)";
        const pbX = 80;
        const pbY = H - 24;
        const pbW = W - 160;
        const pbH = 4;
        ctx.fillRect(pbX, pbY, pbW, pbH);
        ctx.globalAlpha = 1;
        const overallProg = (scene.id - 1 + progress) / scenes.length;
        const progGrad = ctx.createLinearGradient(pbX, 0, pbX + pbW, 0);
        progGrad.addColorStop(0, "#6366f1");
        progGrad.addColorStop(1, "#06b6d4");
        ctx.fillStyle = progGrad;
        ctx.fillRect(pbX, pbY, pbW * overallProg, pbH);

        ctx.font = "11px monospace";
        ctx.fillStyle = "rgba(255,255,255,0.25)";
        ctx.textAlign = "left";
        ctx.fillText("AI THOZHANX 2.O", 80, H - 40);
        ctx.textAlign = "right";
        ctx.fillText(result.title.slice(0, 50), W - 80, H - 40);
        ctx.globalAlpha = 1;
      };

      recorder.start();
      let frame = 0;
      const framesPerScene = SCENE_DURATION_S * FPS;

      await new Promise<void>((resolve) => {
        const tick = () => {
          if (frame >= TOTAL_FRAMES) {
            resolve();
            return;
          }
          const sceneIdx = Math.min(
            Math.floor(frame / framesPerScene),
            scenes.length - 1,
          );
          const sceneProgress = (frame % framesPerScene) / framesPerScene;
          drawScene(scenes[sceneIdx], sceneProgress);
          frame++;
          requestAnimationFrame(tick);
        };
        requestAnimationFrame(tick);
      });

      recorder.stop();
      await new Promise<void>((res) => {
        recorder.onstop = () => res();
      });

      const ext = mimeType.startsWith("video/mp4") ? "mp4" : "webm";
      const blob = new Blob(chunks, { type: mimeType });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `thozhanx-video-${Date.now()}.${ext}`;
      a.click();
      URL.revokeObjectURL(url);
      toast.success(`Video downloaded as .${ext}!`, { id: "vid-dl" });
    } catch (err) {
      console.error(err);
      toast.error("Video export failed", { id: "vid-dl" });
    }
  };

  const handleCopyStoryboard = async () => {
    if (!result) return;
    await copyToClipboard(buildStoryboardText(result));
    toast.success("Storyboard copied!");
  };

  const handleExportToEditor = () => {
    toast.info("Export to Video Editor", {
      description:
        "Download the script then paste it into Premiere Pro, DaVinci Resolve, CapCut, or Canva Video for full production.",
      duration: 6000,
    });
  };

  return (
    <div className="min-h-full p-4 md:p-6" data-ocid="video.page">
      <div className="mx-auto max-w-4xl space-y-6">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -12 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex items-center gap-4"
        >
          <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br from-primary via-secondary to-accent shadow-glow-blue">
            <Video size={22} className="text-primary-foreground" />
          </div>
          <div>
            <h1 className="font-display text-2xl font-bold gradient-text">
              Video Generator
            </h1>
            <p className="text-sm text-muted-foreground">
              🎬 Grok AI Style — Explainer videos, animations, demos
            </p>
          </div>
          <Badge
            variant="outline"
            className="ml-auto hidden sm:flex border-accent/40 text-accent"
          >
            <Sparkles size={11} className="mr-1" /> AI Powered
          </Badge>
        </motion.div>

        {/* Input Panel */}
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="glassmorphism rounded-2xl p-5 space-y-5"
          data-ocid="video.input.panel"
        >
          <div className="space-y-2">
            <Label htmlFor="video-topic" className="text-sm font-semibold">
              What video do you want to create?
            </Label>
            <Textarea
              id="video-topic"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="e.g., How does machine learning work? Explain neural networks for beginners..."
              className="resize-none min-h-[80px] bg-white/5 border-white/10 focus:border-primary/50 text-sm"
              data-ocid="video.topic.textarea"
            />
            <div className="flex flex-wrap gap-2 pt-1">
              {SAMPLE_TOPICS.map((t) => (
                <button
                  key={t}
                  type="button"
                  onClick={() => setTopic(t)}
                  className="flex items-center gap-1 rounded-full border border-accent/30 bg-accent/5 px-3 py-1 text-xs text-accent hover:bg-accent/15 hover:border-accent/60 transition-smooth"
                  data-ocid={`video.sample.${t.toLowerCase().replace(/\s+/g, "-")}`}
                >
                  <Wand2 size={10} /> {t}
                </button>
              ))}
            </div>
          </div>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
            {/* Video type */}
            <div className="space-y-2">
              <Label className="text-xs text-muted-foreground uppercase tracking-wide">
                Video Type
              </Label>
              <div className="flex flex-col gap-1.5">
                {VIDEO_TYPES.map((vt) => (
                  <button
                    key={vt.value}
                    type="button"
                    onClick={() => setVideoType(vt.value)}
                    className={`flex items-center gap-2 rounded-lg px-3 py-1.5 text-xs transition-smooth ${
                      videoType === vt.value
                        ? "bg-primary/20 border border-primary/50 text-primary font-semibold"
                        : "border border-transparent hover:bg-white/5 text-muted-foreground hover:text-foreground"
                    }`}
                    data-ocid={`video.type.${vt.value}`}
                  >
                    <span>{vt.icon}</span> {vt.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Duration + Style */}
            <div className="space-y-2">
              <Label className="text-xs text-muted-foreground uppercase tracking-wide">
                Duration
              </Label>
              <div className="grid grid-cols-2 gap-1.5">
                {DURATIONS.map((d) => (
                  <button
                    key={d.value}
                    type="button"
                    onClick={() => setDuration(d.value)}
                    className={`rounded-lg border px-2 py-2 text-xs font-medium transition-smooth ${
                      duration === d.value
                        ? "border-accent/60 bg-accent/15 text-accent"
                        : "border-border hover:border-accent/30 text-muted-foreground hover:text-foreground"
                    }`}
                    data-ocid={`video.duration.${d.value}`}
                  >
                    {d.label}
                  </button>
                ))}
              </div>

              <Label className="text-xs text-muted-foreground uppercase tracking-wide block mt-3">
                Style
              </Label>
              <div className="grid grid-cols-2 gap-1.5">
                {STYLES.map((s) => (
                  <button
                    key={s.value}
                    type="button"
                    onClick={() => setStyle(s.value)}
                    className={`flex items-center gap-1.5 rounded-lg px-2 py-1.5 text-xs transition-smooth ${
                      style === s.value
                        ? "bg-secondary/20 border border-secondary/50 text-secondary font-semibold"
                        : "border border-transparent hover:bg-white/5 text-muted-foreground hover:text-foreground"
                    }`}
                    data-ocid={`video.style.${s.value}`}
                  >
                    <span
                      className={`h-2 w-2 rounded-full bg-gradient-to-r ${s.color}`}
                    />
                    {s.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Summary + CTA */}
            <div className="flex flex-col justify-between gap-3">
              <div className="rounded-xl border border-white/10 bg-white/5 p-3 space-y-2 text-xs text-muted-foreground">
                <div className="flex items-center gap-2">
                  <Clock size={12} className="text-accent" />
                  <span>
                    Est.{" "}
                    {DURATIONS.find((d) => d.value === duration)?.label ??
                      "2 min"}{" "}
                    video
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <Film size={12} className="text-primary" />
                  <span>5 animated scenes</span>
                </div>
                <div className="flex items-center gap-2">
                  <BookOpen size={12} className="text-secondary" />
                  <span>
                    {VIDEO_TYPES.find((v) => v.value === videoType)?.label ??
                      "Explainer"}
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <Sparkles size={12} className="text-accent" />
                  <span>
                    {STYLES.find((s) => s.value === style)?.label ??
                      "Professional"}{" "}
                    style
                  </span>
                </div>
              </div>
              <Button
                onClick={generate}
                disabled={loading || !topic.trim()}
                className="w-full bg-gradient-to-r from-accent to-primary text-primary-foreground border-0 font-semibold h-11 glow-cyan transition-smooth hover:scale-[1.02] hover:shadow-glow-cyan disabled:opacity-50"
                data-ocid="video.generate.submit_button"
              >
                {loading ? (
                  <Film size={16} className="animate-spin mr-2" />
                ) : (
                  <Play size={16} className="mr-2 fill-current" />
                )}
                {loading ? "Generating…" : "Generate Video"}
              </Button>
            </div>
          </div>
        </motion.div>

        {/* Generation progress */}
        <AnimatePresence>
          {loading && (
            <motion.div
              initial={{ opacity: 0, y: -8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0 }}
              className="glassmorphism rounded-2xl p-5 space-y-3"
              data-ocid="video.loading_state"
            >
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-primary/20 to-accent/20 animate-pulse">
                  <Film size={18} className="text-accent" />
                </div>
                <div className="flex-1">
                  <p className="text-sm font-semibold text-foreground">
                    Generating your video script…
                  </p>
                  <p className="text-xs text-muted-foreground">
                    Building scenes, narration &amp; storyboard
                  </p>
                </div>
                <span className="text-sm font-bold text-accent">
                  {genProgress}%
                </span>
              </div>
              <div className="h-2 overflow-hidden rounded-full bg-border">
                <motion.div
                  className="h-full rounded-full bg-gradient-to-r from-primary via-secondary to-accent"
                  animate={{ width: `${genProgress}%` }}
                  transition={{ duration: 0.4, ease: "easeOut" }}
                />
              </div>
              <div className="flex justify-between text-[10px] text-muted-foreground">
                <span>Analyzing</span>
                <span>Writing narration</span>
                <span>Building scenes</span>
                <span>Finalizing</span>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Empty state */}
        {!result && !loading && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="glassmorphism rounded-2xl p-14 text-center"
            data-ocid="video.empty_state"
          >
            <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-primary/10 to-accent/10 border border-white/10">
              <Video size={28} className="text-muted-foreground/40" />
            </div>
            <p className="font-display font-semibold text-muted-foreground">
              No video generated yet
            </p>
            <p className="mt-1 text-sm text-muted-foreground/60">
              Enter a topic above and click Generate to create your video script
              &amp; storyboard
            </p>
          </motion.div>
        )}

        {/* Output section */}
        <AnimatePresence>
          {result && (
            <motion.div
              key="result"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
              className="space-y-5"
              data-ocid="video.result.section"
            >
              <MockVideoPlayer script={result} />

              <div className="glassmorphism rounded-2xl p-5">
                <Tabs defaultValue="storyboard" data-ocid="video.output.tabs">
                  <TabsList className="w-full bg-muted/30 p-1 mb-5">
                    <TabsTrigger
                      value="storyboard"
                      className="flex-1 gap-1.5 data-[state=active]:bg-primary data-[state=active]:text-primary-foreground"
                      data-ocid="video.tab.storyboard"
                    >
                      <Layers size={13} /> Storyboard
                    </TabsTrigger>
                    <TabsTrigger
                      value="script"
                      className="flex-1 gap-1.5 data-[state=active]:bg-primary data-[state=active]:text-primary-foreground"
                      data-ocid="video.tab.script"
                    >
                      <Film size={13} /> Full Script
                    </TabsTrigger>
                    <TabsTrigger
                      value="notes"
                      className="flex-1 gap-1.5 data-[state=active]:bg-primary data-[state=active]:text-primary-foreground"
                      data-ocid="video.tab.notes"
                    >
                      <Settings2 size={13} /> Production
                    </TabsTrigger>
                  </TabsList>

                  <TabsContent value="storyboard" className="mt-0">
                    <div className="flex items-center justify-between mb-4">
                      <h3 className="font-display font-semibold text-foreground">
                        {result.title}
                      </h3>
                      <div className="flex items-center gap-3 text-xs text-muted-foreground">
                        <span className="flex items-center gap-1">
                          <Film size={11} /> {result.scenes.length} scenes
                        </span>
                        <span className="flex items-center gap-1">
                          <Clock size={11} /> {result.duration}s
                        </span>
                      </div>
                    </div>
                    <div>
                      {result.scenes.map((scene, i) => (
                        <SceneCard
                          key={scene.id}
                          scene={scene}
                          index={i}
                          narration={result.narration}
                          isLast={i === result.scenes.length - 1}
                        />
                      ))}
                    </div>
                  </TabsContent>

                  <TabsContent value="script" className="space-y-4 mt-0">
                    <div className="flex items-center justify-between">
                      <h3 className="font-display font-semibold text-foreground">
                        Full Narration Script
                      </h3>
                      <div className="flex items-center gap-3 text-xs text-muted-foreground">
                        <span className="flex items-center gap-1">
                          <Clock size={11} /> {result.duration}s
                        </span>
                        <span className="flex items-center gap-1">
                          <Film size={11} /> {wordCount(result.narration)} words
                        </span>
                      </div>
                    </div>
                    <Separator className="opacity-20" />

                    <div className="grid grid-cols-3 gap-3 text-center">
                      {[
                        {
                          icon: Clock,
                          label: "Duration",
                          value: `${result.duration}s`,
                        },
                        {
                          icon: Film,
                          label: "Scenes",
                          value: result.scenes.length.toString(),
                        },
                        {
                          icon: BookOpen,
                          label: "Words",
                          value: wordCount(result.narration).toString(),
                        },
                      ].map(({ icon: Icon, label, value }) => (
                        <div
                          key={label}
                          className="rounded-xl border border-border bg-muted/30 p-3"
                        >
                          <Icon
                            size={16}
                            className="mx-auto mb-1 text-accent"
                          />
                          <p className="font-display font-bold text-foreground">
                            {value}
                          </p>
                          <p className="text-[10px] text-muted-foreground">
                            {label}
                          </p>
                        </div>
                      ))}
                    </div>

                    <div
                      className="rounded-xl border border-border bg-muted/20 p-4"
                      data-ocid="video.script.content"
                    >
                      <div className="flex items-center justify-between mb-3">
                        <p className="font-semibold text-xs uppercase tracking-wide text-muted-foreground">
                          Full Narration
                        </p>
                        <button
                          type="button"
                          onClick={() => setShowSceneNarrations((s) => !s)}
                          className="text-xs text-accent hover:text-accent/80 transition-smooth"
                          data-ocid="video.script.toggle"
                        >
                          {showSceneNarrations
                            ? "Collapse scenes"
                            : "Expand per scene"}
                        </button>
                      </div>
                      <p className="text-sm leading-7 text-foreground">
                        {result.narration}
                      </p>

                      <AnimatePresence>
                        {showSceneNarrations && (
                          <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: "auto" }}
                            exit={{ opacity: 0, height: 0 }}
                            className="overflow-hidden"
                          >
                            <div className="mt-4 space-y-3 border-t border-border pt-4">
                              {result.scenes.map((scene) => (
                                <div
                                  key={scene.id}
                                  className="rounded-lg bg-card/50 p-3"
                                >
                                  <p className="text-xs font-semibold text-accent mb-1">
                                    Scene {scene.id}: {scene.title}
                                  </p>
                                  <p className="text-xs text-foreground/80 italic">
                                    "
                                    {getNarrationForScene(
                                      scene,
                                      result.narration,
                                    )}
                                    "
                                  </p>
                                </div>
                              ))}
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
                  </TabsContent>

                  <TabsContent value="notes" className="mt-0 space-y-3">
                    <p className="text-xs text-muted-foreground">
                      Production specifications and style guide for "
                      {result.title}".
                    </p>
                    {PRODUCTION_NOTES.map((item) => (
                      <div
                        key={item.label}
                        className="flex items-start gap-3 rounded-lg border border-border bg-muted/20 px-4 py-2.5"
                      >
                        <span className="shrink-0 w-28 text-xs font-semibold text-muted-foreground">
                          {item.label}
                        </span>
                        <Separator
                          orientation="vertical"
                          className="h-4 opacity-30 self-center"
                        />
                        <span className="text-xs text-foreground">
                          {item.value}
                        </span>
                      </div>
                    ))}
                  </TabsContent>
                </Tabs>
              </div>

              {/* Export options */}
              <div
                className="glassmorphism rounded-2xl p-4 space-y-3"
                data-ocid="video.export.panel"
              >
                <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">
                  Export Options
                </p>
                <div className="flex flex-wrap gap-3">
                  <Button
                    variant="outline"
                    className="border-primary/30 bg-primary/10 text-primary hover:bg-primary/20 flex-1 min-w-[140px]"
                    onClick={handleCopyScript}
                    data-ocid="video.export.copy_script_button"
                  >
                    <Copy size={14} className="mr-2" /> Copy Full Script
                  </Button>
                  <Button
                    variant="outline"
                    className="border-accent/30 bg-accent/10 text-accent hover:bg-accent/20 flex-1 min-w-[140px]"
                    onClick={handleDownloadScript}
                    data-ocid="video.export.download_script_button"
                  >
                    <Download size={14} className="mr-2" /> Download MP4
                  </Button>
                  <Button
                    variant="outline"
                    className="border-secondary/30 bg-secondary/10 text-secondary hover:bg-secondary/20 flex-1 min-w-[140px]"
                    onClick={handleCopyStoryboard}
                    data-ocid="video.export.copy_storyboard_button"
                  >
                    <Copy size={14} className="mr-2" /> Copy Storyboard
                  </Button>
                  <Button
                    variant="outline"
                    className="border-border bg-muted/20 text-foreground hover:bg-muted/40 flex-1 min-w-[140px]"
                    onClick={handleExportToEditor}
                    data-ocid="video.export.editor_button"
                  >
                    <ExternalLink size={14} className="mr-2" /> Export to Video
                    Editor
                  </Button>
                </div>
                <p className="text-[11px] text-muted-foreground/60 flex items-center gap-1.5">
                  <Sparkles size={10} />
                  Use this script in Premiere Pro, DaVinci Resolve, CapCut, or
                  Canva Video for full production.
                </p>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
