/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GenerationType = IDL.Variant({
  'PDF' : IDL.Null,
  'PPT' : IDL.Null,
  'Chat' : IDL.Null,
  'Website' : IDL.Null,
  'Image' : IDL.Null,
  'Document' : IDL.Null,
  'Abstract' : IDL.Null,
  'Project' : IDL.Null,
  'Video' : IDL.Null,
});
export const Generation = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'type' : GenerationType,
  'prompt' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'joinedAt' : IDL.Int,
  'totalGenerations' : IDL.Nat,
});

export const idlService = IDL.Service({
  'deleteGeneration' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
  'getActiveUsers' : IDL.Func([], [IDL.Nat], ['query']),
  'getGenerationHistory' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Vec(Generation)],
      ['query'],
    ),
  'getTotalGenerations' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'saveGeneration' : IDL.Func(
      [IDL.Principal, GenerationType, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'updateUserProfile' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GenerationType = IDL.Variant({
    'PDF' : IDL.Null,
    'PPT' : IDL.Null,
    'Chat' : IDL.Null,
    'Website' : IDL.Null,
    'Image' : IDL.Null,
    'Document' : IDL.Null,
    'Abstract' : IDL.Null,
    'Project' : IDL.Null,
    'Video' : IDL.Null,
  });
  const Generation = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'type' : GenerationType,
    'prompt' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'joinedAt' : IDL.Int,
    'totalGenerations' : IDL.Nat,
  });
  
  return IDL.Service({
    'deleteGeneration' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
    'getActiveUsers' : IDL.Func([], [IDL.Nat], ['query']),
    'getGenerationHistory' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Vec(Generation)],
        ['query'],
      ),
    'getTotalGenerations' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'saveGeneration' : IDL.Func(
        [IDL.Principal, GenerationType, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'updateUserProfile' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };