/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Generation {
  'id' : string,
  'title' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'type' : GenerationType,
  'prompt' : string,
}
export type GenerationType = { 'PDF' : null } |
  { 'PPT' : null } |
  { 'Chat' : null } |
  { 'Website' : null } |
  { 'Image' : null } |
  { 'Document' : null } |
  { 'Abstract' : null } |
  { 'Project' : null } |
  { 'Video' : null };
export interface UserProfile {
  'principal' : Principal,
  'displayName' : string,
  'joinedAt' : bigint,
  'totalGenerations' : bigint,
}
export interface _SERVICE {
  'deleteGeneration' : ActorMethod<[Principal, string], boolean>,
  'getActiveUsers' : ActorMethod<[], bigint>,
  'getGenerationHistory' : ActorMethod<[Principal, bigint], Array<Generation>>,
  'getTotalGenerations' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'saveGeneration' : ActorMethod<
    [Principal, GenerationType, string, string],
    string
  >,
  'updateUserProfile' : ActorMethod<[Principal, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];